[package]
name = "tarea1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
nix = "0.24.2"
linux-personality = "1.0.0"
termios = "0.3.3"
